- name: Sync Code to Databricks Workspace
        env:
          DATABRICKS_HOST: "https://adb-7405619629697022.2.azuredatabricks.net"
          DATABRICKS_AUTH_TYPE: "azure-cli"
        run: |
          echo "Syncing repository source files to user workspace..."
          databricks sync ./src /Users/sqlken_msn.com#ext#@sqlkenmsn.onmicrosoft.com/kazure-pipeline/
